[meta]
name     = "MLHook & Event Inspector"
author   = "XertroV"
category = "MLHook"
version  = "0.1.6"

[script]
#__DEFINES__
exports = [ "Export.as" ] # no src/ prefix b/c of build.sh
shared_exports = [ "ExportShared.as" ] # no src/ prefix b/c of build.sh
# dependencies = [ 'MLHook' ]
